### ISSUE TITLE
So, what about mod files actualy?

### ISSUE THREAD

**Issue by KrsKonst** [SnuggleButtPrincess/Lustful-Void#1]
Hey.

I've tried your mod and I liked it. 

And I wanted to add russian localisation. I thought: 'I saw a link to github in mod description. Great. I'll just clone it, make all nececary additions and commit a pull request'. But when I came here, all I found where a readme file and some config whith theme.
So, do you have plans to publish mod files here?

Best, Konst

**Comment by cgiAlexis** [comment]
Branch the main mod to your own space, then assuming that the "top" of the tree is the root of the mod "\Lustful Void\" add your files.

Create a folder called "Localisation" and within that "Russian" (Or would that be "русский"). Then place your own localisation files in there.

This way SnuggleButt should be able to see your branch and when they're happy they can request a merge of your branch to the main branch

**Comment by KrsKonst** [comment]
Strange workflow.
But I got you. Thanks.
